import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  PROCGEN_COURSE_SPAWN_FIXTURE_CASES,
  createProcgenCourseSpawnFixture,
} from "../src/mhs/ProcgenCourseSpawnFixtures";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(repoRoot, "..");
const outPath = resolve(
  workspaceRoot,
  "putt_realms",
  "scripts",
  "puttrealms",
  "procgen",
  "ProcgenCourseFixtures.ts",
);

const fixtureEntries = PROCGEN_COURSE_SPAWN_FIXTURE_CASES.map((fixtureCase) => ({
  name: fixtureCase.name,
  course: createProcgenCourseSpawnFixture(fixtureCase).course,
}));

const body = `// @generated by putt-realms-main/scripts/export-mhs-procgen-fixtures.ts
// Source contract: putt-realms-main/src/mhs/ProcgenCourseSpawnV1.ts

import type { ProcgenCourseSpawnV1 } from "./ProcgenCourseSpawnTypes";

export interface CourseFixtureEntry {
  name: string;
  course: ProcgenCourseSpawnV1;
}

export const COURSE_FIXTURES: CourseFixtureEntry[] = ${JSON.stringify(fixtureEntries, null, 2)};

export function getCourseFixture(name: string): ProcgenCourseSpawnV1 {
  for (const fixture of COURSE_FIXTURES) {
    if (
      fixture.name === name ||
      fixture.course.levelId === name ||
      fixture.course.procgenSeed === name
    ) {
      return fixture.course;
    }
  }
  throw new Error("[PuttRealms] Unknown procgen fixture: " + name);
}
`;

writeFileSync(outPath, body);
console.log(`Wrote ${fixtureEntries.length} procgen fixtures to ${outPath}`);
